### ISSUE TITLE
OSCORE key derivation

### ISSUE THREAD

**Issue by DurandA** [HappyEmu/ace#1]
When reading [draft-ietf-core-object-security-08](https://tools.ietf.org/html/draft-ietf-core-object-security-08), I noticed they settled on HKDF ([RFC5869](https://tools.ietf.org/html/rfc5869)) — with HKDF SHA-256 being mandatory) for key derivation.

Should HKDF replace EDHOC? I also noticed that both [draft-ietf-core-object-security-08](https://tools.ietf.org/html/draft-ietf-core-object-security-08) and [draft-selander-ace-cose-ecdhe-07](https://tools.ietf.org/html/draft-selander-ace-cose-ecdhe-07) are from the same authors.

**Comment by HappyEmu** [comment]
Not sure if I understand the question correctly. 

HKDF is only used to derive keys from a previously established master secret. How this master secret is established is being left to the application to implement and it's exactly what EDHOC does:

![image](https://user-images.githubusercontent.com/1112149/36090118-5818ecc4-0fdf-11e8-8f4f-81c3c8149353.png)

After EDHOC, we end up with all the required parameters (master secret, master salt, recipient and sender IDs, HKDF, AEAD, etc...)

**Comment by HappyEmu** [comment]
The workflow implemented right now is the one described in Appendix B (and B.1) of [https://www.ietf.org/id/draft-ietf-ace-oscore-profile-00.txt](https://www.ietf.org/id/draft-ietf-ace-oscore-profile-00.txt) where we use the PoP key bound to the access token to authenticate the messages in EDHOC.

**Comment by DurandA** [comment]
Thanks for the clarification.
