### ISSUE TITLE
Nonce mismatch on EDHOC session

### ISSUE THREAD

**Issue by DurandA** [HappyEmu/ace#5]
Using the provided example, `client` and `server` have a different context:
https://github.com/HappyEmu/ace/blob/13ae2ff9d2cd400e1e6701f673eb0355b5446d96/lib/edhoc/protocol.py#L293-L313

The OSCORE master secret is the same while the master salt is different. Moreover, the client has a 7-bit salt while the server has a 8-bit salt.

**Comment by DurandA** [comment]
The HKDF key length mismatch in `_calculate_oscore_context` between `edhoc.protocol.Server` and  `edhoc.protocol.Client`.

This is fixed by setting a length of 7 instead of 8 in `Server`:
```patch
-        oscore_master_salt = derive_key(self.session.shared_secret, length=64 // 8,
-                                        context_info=cose_kdf_context("EDHOC OSCORE Master Salt", 64 // 8,
+        oscore_master_salt = derive_key(self.session.shared_secret, length=56 // 8,
+                                        context_info=cose_kdf_context("EDHOC OSCORE Master Salt", 56 // 8,
                                                                       other=exchange_hash))
```

**Comment by HappyEmu** [comment]
Yes, I'll need to adapt some code to get the python server and client compatible again. I'll probably get to this tomorrow.
